### ISSUE TITLE
ReferenceError: Can't find variable: Buffer

### ISSUE THREAD

**Issue by dnaicker** [jolocom/jolocom-lib#461] opened 2021-07-08 08:30 UTC
**Describe the bug**
When creating a self sovereign identity using instructions from https://jolocom-lib.readthedocs.io/en/latest/gettingStarted.html Section 1.2 inside a React Native application:
`import { walletUtils } from '@jolocom/native-core'
import { SoftwareKeyProvider } from '@jolocom/vaulted-key-provider'

const password = 'secretpassword'

SoftwareKeyProvider.newEmptyWallet(walletUtils, 'id:', password).then(emptyWallet => {
  console.log(emptyWallet)
})
`

**To Reproduce**
1. Create new react-native project using expo cli: npm install -g expo-cli, expo init AwesomeProject, cd AwesomeProject
2. Install Jolocom lib: npm install jolocom-lib --save, and optional install sdk: npm i @jolocom/sdk jolocom-lib
3. Run npm start
4. See error: 
`import { walletUtils } from '@jolocom/native-core'
import { SoftwareKeyProvider } from '@jolocom/vaulted-key-provider'

const password = 'secretpassword'

SoftwareKeyProvider.newEmptyWallet(walletUtils, 'id:', password).then(emptyWallet => {
  console.log(emptyWallet)
})
`

**Expected behavior**
To create new empty wallet and log output to console of wallet creation.

**Screenshots**
![image](https://user-images.githubusercontent.com/7840952/124889330-485dc680-dfd7-11eb-9bd6-156ad2911321.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Android Emulator
 - version 11, API 30

**Smartphone (please complete the following information):**
 - Android Emulator
 - 11
 - Chrome
 
**Additional context**
I am using React-Native 0.64, Node version 14.17.3, Ubuntu 20

**Comment by serg-temchenko** [comment] 2021-07-14 13:39
Hello @dnaicker.
It looks like the problem is in the build process it self and the way in which order the packages are loaded.
Did you checked/tried the configuration in the notice on the page you are [linked](https://jolocom-lib.readthedocs.io/en/latest/gettingStarted.html) (under 1.1 point)?
> To use the library in a browser or a react native environment additional polyfilling is required. For an example of integrating this library with a react native application, please see the [Jolocom SmartWallet metro configuration.](https://github.com/jolocom/smartwallet-app/blob/develop/metro.config.js)

If not - pleas check and tell if that helps...
Right away I think that issue can be resolved by declaring the global `Buffer` variable in the file, where `@jolocom/vaulted-key-provider` is used. Like this:

`global.Buffer = global.Buffer || require('buffer').Buffer`

But it looks a bit hacky and I think there is more appropriate way to resolve this issue, will get back to this when will have some time...

**Comment by dnaicker** [comment] 2021-07-14 18:20
@serg-temchenko Thank you for responding to my issue. I have used the metro file https://github.com/jolocom/smartwallet-app/blob/develop/metro.config.js in root of application folder, it resolved previous build errors.

Thank you again much appreciated.

**Comment by serg-temchenko** [comment] 2021-07-15 13:08
Issue seems to be resolved.

**Closed as completed by serg-temchenko** 2021-07-15 13:08 UTC

**Comment by dnaicker** [comment] 2021-07-15 14:23
@serg-temchenko Thank you soo much! I was just wondering how do I get the latest build? I did an npm update but it did not download any new update.

**Comment by serg-temchenko** [comment] 2021-07-15 15:33
Hey @dnaicker
Can you please provide `package.json` line where defined `jolocom-lib` dependency?

**Comment by dnaicker** [comment] 2021-07-15 16:01
@serg-temchenko thanks for replying. The line is: "jolocom-lib": "^5.2.1",

![image](https://user-images.githubusercontent.com/7840952/125819664-2b67a4b1-0b22-4863-a25b-7e30460e5c3b.png)

**Comment by serg-temchenko** [comment] 2021-07-16 00:45
@dnaicker thanks for the output.
It looks like you have installed the latest published version from the npm registry.
There are still couple of RC (release candidate) versions `jolocom-lib-v5.2.2-rc2-gitpkg`, `jolocom-lib-v5.2.2-rc3-gitpkg`, `jolocom-lib-v5.3.0-rc5-gitpkg` which has been released as a git tags (not published on the npm).

Despite that you still can test those versions by changing: `"jolocom-lib": "^5.2.1"` on `"jolocom-lib": "jolocom/jolocom-lib#jolocom-lib-v5.3.0-rc5-gitpkg"` to use the latest RC tag.

**Comment by dnaicker** [comment] 2021-07-16 07:02
@serg-temchenko thank you Serg for providing instructions on how to update. I have created a new project with expo cli, added "jolocom-lib": "jolocom/jolocom-lib#jolocom-lib-v5.3.0-rc5-gitpkg", confirmed that I do have the correct node module

![image](https://user-images.githubusercontent.com/7840952/125906001-d6fb7da1-40c5-4926-9afd-e91f3ef42acc.png)

but i receive the buffer error again:

![image](https://user-images.githubusercontent.com/7840952/125905939-79da1a26-05ea-426b-8394-ba22b10ebc6b.png)
 
my app.js file code is: 

![image](https://user-images.githubusercontent.com/7840952/125906048-bea19b18-4763-4d87-a6f4-9b79b4ee5c67.png)

my package json is:
![image](https://user-images.githubusercontent.com/7840952/125906113-3c868b28-4d5b-4d32-ac27-c42d86167531.png)
